services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    container_name: ${DATABASE_CONTAINER_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${VOLUME_STORAGE}:/var/lib/postgresql/data


  redis:
    image: redis:7.4.0-alpine
    restart: always
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  app:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: ${APP_CONTAINER_NAME}
      ports:
        - "${BACKEND_PORT}:3000" 
      depends_on:
        - db
        - redis
      env_file:
        - .env
      environment:
        DATABASE_HOST: db
        REDIS_HOST: redis
      
volumes:
  db: